@Backend_HostAddress = http://localhost:5291

GET {{Backend_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Backend_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "fullName": "Test Kullanici",
  "email": "test@example.com",
  "password": "Test1234!"
}

###
